server:
  port: 8003
spring:
  application:
    name: sb-mp-dr-redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: 123456kid
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #默认日期格式转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
# mybatis- plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #开发环境打印执行的sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
