server:
  port: 8087
spring:
  application:
    name: n-f-sb-redisson
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848