server:
  port: 8087
spring:
  application:
    name: n-f-sb-mq
  rabbitmq:
    host: 192.168.0.106
    port: 5672
    virtualHost: /
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #默认日期格式转换
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: always
